# Generated by Django 3.2.9 on 2021-11-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='enter course name', max_length=200, unique='True', verbose_name='course_name'),
        ),
    ]
